### ISSUE TITLE
Light weight cache invalidation

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#198]
An obvious pattern when using the SolrWayback bundle is to check indexing progress using SolrWayback and the internal SolrWayback caching of results means outdated responses. the cache should be invalidated when the number of indexed documents changes.

Unfortunately even a "null"-query such as `q=*:*&rows=0&facet=false&group=false&hl=false` is non-trivial for billions of documents. It seems reasonable that there should be _some_ way of detecting if the index has been changed, but how!?

One solution would be to have a heartbeat checker running in the background, invalidating all caches if the number of documents in the index changes. But this risks outdated results and puts a recurring load on the index.

**Comment by thomasegense** [comment]
We can use the index_time field. 
First extract maximum index_time. This is only required to be queried once at startup:
http://localhost:8983/solr/netarchivebuilder/select?q=*:*&rows=0&stats.field={!max=true}index_time&stats=true

If the maximum value is:2021-10-28T19:03:39.134Z
Then you make the range query: index_time:{2021-10-28T19:03:39.134ZTO *] 
This query will exclude the minimum value. (curly bracket instead of square bracket)
If there is nothing new this will be the empty set and the query seems instant. 

@tokee  Confirm please :)

**Comment by tokee** [comment]
Seems like the right idea, @thomasegense! And as we discussed, we're going with the background checker principle, using `TimerTask`.
