### ISSUE TITLE
Add collection support

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#221]
There are two kinds of collections in this scenario:
* SolrCloud collections (aka logical indexes)
* warc-indexer collections (stated on the command line when indexing the WARCs)

SolrWayback has no explicit support for either, but a current workaround is to make warc-indexer collections a facet, like `domain` and `year`. There are at least 2 user experience problems with this approach:

1. The user has to perform a search before it is possible to select a collection (this could be mitigated by performing a *:*-search automatically)
2. The collection-facet is just a facet like all the rest. If the overall scenario is that common searches will span all collections, this would be fine. If it is not, it is a huge stumble, especially when combined with number 1: "_To see our COVID-19 collection, first perform a search for `*:*`, then locate the collections facet and choose COVID-19_".

So what can we do?
* Performing some GUI-adjustments to make warc-indexer collections first class (a drop-down box or similar) should be fairly simple, so maybe we should start there?
* Adding support for SolrCloud collections would require more work under the hood.

Having a combination of both sounds like a perfect recipe for confusion, so maybe it should be either-or?

**Comment by thomasegense** [comment]
Out in the wild users are already using the collection field and also collection_id field and have facets on these.
Since it is now possible to create a large 'about collection' pop-up text the different collections can be described there.

A drop-down for collection selection together with a query can also cause confusion why results are not found. And you can argue that content_type_norm also should have a drop-down. 

I will create a new jira when I hear the community ask for this,
