### ISSUE TITLE
Thumbnails not displayed in image search with playback disabled

### ISSUE THREAD

**Issue by jorntx** [netarchivesuite/solrwayback#229]
After the property for disabling playback was introduced image search (standard search filtered to images) does not display thumbs. The reason for this is that this view uses the full image to display thumbs and this is disabled when playback property is set to false.  The page-resources lists also shows images and the same fix should be applied here. 

Steps to reproduce:

1. Make a standard search
2. Apply images facet
3. See the broken image tag and endless spinner

Proposed fix:
Use same thumbnail display mechanism/template as used when displaying thumbs in HTML results

The issue is fixed in backend until it has been fixed in the frontend. It is a big ugly and image will be returned as Octet-Stream.

**Comment by jorntx** [comment]
I think I need clarification as to the proposed fix: "Use same thumbnail display mechanism/template as used when displaying thumbs in HTML results"

HTML and standard results all display the same image-behaviour as the image search result.

**Comment by thomasegense** [comment]
Decided to live with the hack in the backend as this is much quicker that rewrite frontend logic.
The only disadvantage is the image will be returned with content-type Octet-Stream instead of the correct image type.
But the browsers will show the images perfect anyway. And the disabled playback mode is not a very common use of SolrWayback.
