### ISSUE TITLE
Refine time frame and time scale on Ngram Netarchive

### ISSUE THREAD

**Issue by saraaubry** [netarchivesuite/solrwayback#295]
On the same model as issue https://github.com/netarchivesuite/solrwayback/issues/270, this feature will give users the possiblity to set a time frame and time scale to refine the curves.

**Comment by thomasegense** [comment]
@bnfleb 
Guess you are working on this?

**Comment by saraaubry** [comment]
Ngram currently uses a cache system where request results overlap until the user resets everything.
Adding refine time frame and time scale possibilities raises ergonomics questions: we cannot overlap results at different time scale but how can we alert users? 
With @bnfleb, we see 2 possibilities:
1) Block dates fields after the first request. Disadvantages: it is not easy to explain why these filters are disabled. Alothough these filters could enable them to zoom at a certain period of time.
2) Replace the cache system and give users the possibility to use a coma to search for multiple terms or expressions.
What do you think @thomasegense?

**Comment by thomasegense** [comment]
Yes, I forgot the cached year-facet (total results), which are required to calculate to percentage of hits for each year.

You solution 1) seems the best. 
Since Solr queries are cached in SolrWayback (default configuration and until index changes), there is no need to actual 
save the cache (days/weeks/months etc.). The cache will last long enough for the user to have finished using the n-gram component. The solr query will be indentical, and thus saved in the cache. The method in NetarchiveSolrClient must specify that it used the cached solr-client implementation. But the first search will take a long time since it is not in the cache. 
So to put it short: Instead of using cache, always query Solr if buckets is day/week/month.

It is not an option to try calculate to cache for all days/weeks/months since this does not scale to our collection size.
And trying to maintaining and pieces together a cache from different day ranges from different n-gram searches is not worth
all that hard work, when it is unlikely it even will be reused.

@bnfleb What you think?

**Comment by bnfleb** [comment]
Actually, there are two caches : 
- in java, for the total results in a custom class (NetarchiveYearCountCache)
- in the front side (vue store), for the query results (count, percent, total and query). These datas are stored to be compared with each other

What I can do is remove the NetarchiveYearCountCache and use the already implemented cache of Solrwayback and for the front part, store the time frame and time scale, add a tooltip on the refine options when disabled to explain why it is disabled. The text "Visualization of search query by year" must also be modified.

@thomasegense are you ok with this ?

**Comment by thomasegense** [comment]
Yes, I agree.

There will be some performance degeneration by removing the year cache for large collections. But the code will also be simpler instead of having two different cases. Researchers must expect some delay for toolbox functionality. The wordcloud also takes 30 seconds on a large corpus.

**Comment by saraaubry** [comment]
@bnfleb implemented this feature. As a follow up to the points mentioned above, we have adapted the following points:

1) The cache is reset (and the search reset to 0) if there is any change in the dates or the scale.
 
2) Labels, tooltips and legend have been adapted according to the scale (YYYY, YYYY-MM, YYYY-MM-DD), on the graph and in the export.

3) The queries from the points of the graph have been adapted to take into account the day 1 and the defined period.

4) The presentation text has been updated.

**Comment by saraaubry** [comment]
Also fixes : https://github.com/netarchivesuite/solrwayback/issues/301

**Comment by thomasegense** [comment]
Merged closed.

**Comment by bnfleb** [comment]
The main developpements for ngram are in PR #318, those in PR #315 are common methods for visualisation, domain stats and ngram.
