### ISSUE TITLE
Sort results by date ascending and descending

### ISSUE THREAD

**Issue by saraaubry** [netarchivesuite/solrwayback#311]
Give users the possibility to sort the results by ascending and descending date in addition to score calculated by Solr.
Add a drop-down menu, on the same line as the navigation between the results pages, on the right, with: score (default value), date asc , date desc.

@bnfleb worked on this.

**Comment by thomasegense** [comment]
The position of the drop-down select is very intuitive. Looks good. 

I will add to the documentation that exports like CSV will still be sorted by ranking. The user can just sort it after downloading. For WARC-files sorting does not really matter.

Due to limitations of Solr it is not something that can be implemented effective on SolrCloud anway.
