### ISSUE TITLE
Playback bug. Replacing img-src tags having '&amp;' characters

### ISSUE THREAD

**Issue by thomasegense** [netarchivesuite/solrwayback#416]
This error is rare and seems to happen with `&amp;`  encoding for parameter values in src-set url.

The following are references to internal server.

Playback of this page, does not show images from img-src, due to normalization error.
(replace production SERVER)
https://SERVER:4000/solrwayback/search?query=arc_job%3A432598%20AND%20url%3A%22https%3A%2F%2Fwww.dr.dk%2Fnyheder%2Findland%2Flandsbyer-trodser-butiksdoed-borgere-i-over-100-byer-har-finansieret-deres-egen%22&grouping=false&imgSearch=false&offset=0&urlSearch=false&facets=&sort=score%20desc

This is the URL from the srcset in the html raw source of that page (the last 2550w is removed correct).

 **https://asset.dr.dk/imagescaler/?protocol=https&amp;server=www.dr.dk&amp;file=%2Fimages%2Fcrop%2F2023%2F09%2F08%2F1694173578_scanpix-20230908-132100-7.jpg&amp;scaleAfter=crop&amp;quality=30&amp;w=2550&amp;h=1434 2550w**

Searching for this url, using url_norm works and the image is found:
**url_norm:"http://asset.dr.dk/imagescaler/?protocol=https&amp;server=www.dr.dk&amp;file=/images/crop/2023/09/08/1694173578_scanpix-20230908-132100-7.jpg&amp;scaleafter=crop&amp;quality=30&amp;w=2550&amp;h=1434"**

The problem is that the HtmlParserUrlRewriter  does calculate the url_norm correct.
The url is replaces with this value instead:

**url_norm:"http://asset.dr.dk/imagescaler/?protocol=https&server=www.dr.dk&file=/images/crop/2023/09/08/1694173578_scanpix-20230908-132100-7.jpg&scaleafter=crop&quality=30&w=2550&h=1434"**

And this image is not found in the collection.

The difference is the `&amp;` has been  decoded and replaced  with `&`

Notice that both url_norm's are indeed working on the live web and points to the image on that remote server.

**Comment by tokee** [comment]
Not sure the error is in the rewriter...

The HTML contain a link ala
```
<img ... srcset="https://asset.dr.dk/imagescaler/?protocol=https&amp;server=www.dr.dk&amp;file=%2Fimages%2Fcrop%2F2023%2F09%2F08%2F1694173578_scanpix-20230908-132100-7.jpg&amp;scaleAfter=crop&amp;quality=30&amp;w=2550&amp;h=1434 2550w" .../>
```
the `srcset` is an attribute so the value from there must be entity-decoded when we retrieve it so we get
```
https://asset.dr.dk/imagescaler/?protocol=https&server=www.dr.dk&file=%2Fimages%2Fcrop%2F2023%2F09%2F08%2F1694173578_scanpix-20230908-132100-7.jpg&scaleAfter=crop&quality=30&w=2550&h=1434 2550w
```
If we did a direct URL lookup, without normalisation, this would be the value to look for. But we do normalisation and for the URL in question this removes the `s` in `https` and URLDecodes the `%2F` to `/`:
```
http://asset.dr.dk/imagescaler/?protocol=https&server=www.dr.dk&file=/images/crop/2023/09/08/1694173578_scanpix-20230908-132100-7.jpg&scaleAfter=crop&quality=30&w=2550&h=1434
```
This matches with the description for this issue, but also seems to me to be correct behavior!?

The expansion of `&` to `&amp;` seems like a quite strange thing to do in an URL-normalisation

This calls for deeper digging and I hope it does not mean our indexed `url_norm`s are even more borked than already known!

**Comment by tokee** [comment]
Addendum: The page is still live. If one visits https://www.dr.dk/nyheder/indland/landsbyer-trodser-butiksdoed-borgere-i-over-100-byer-har-finansieret-deres-egen in one of the common browsers, right clicks on the image and copy the image link, this gets returned: https://asset.dr.dk/imagescaler/?protocol=https&server=www.dr.dk&file=%2Fimages%2Fcrop%2F2023%2F09%2F08%2F1694173578_scanpix-20230908-132100-7.jpg&scaleAfter=crop&quality=70&w=850&h=478 (the link works fine and returns the image).

No `&amp;` in sight. Unfortunately that asset does not exist in Netarchive Search (by direct `url`-field search).

However, if the following call (note the use of `&amp;`) is performed on the primary Solr Cloud server for Netarchive Search:
```
curl -gs 'http://localhost:52301/solr/ns/select' --data-urlencode 'q=url:"https://asset.dr.dk/imagescaler/?protocol=https&amp;server=www.dr.dk&amp;file=%2Fimages%2Fcrop%2F2023%2F09%2F08%2F1694173578_scanpix-20230908-132100-7.jpg&amp;scaleAfter=crop&amp;quality=30&amp;w=2550&amp;h=1434"' -d 'fl=url,url_norm' -d 'rows=1' -d 'wt=json'
```
it returns
```
      {
        "url_norm":"http://asset.dr.dk/imagescaler/?protocol=https&amp;server=www.dr.dk&amp;file=/images/crop/2023/09/08/1694173578_scanpix-20230908-132100-7.jpg&amp;scaleafter=crop&amp;quality=30&amp;w=2550&amp;h=1434",
          "url":"https://asset.dr.dk/imagescaler/?protocol=https&amp;server=www.dr.dk&amp;file=%2Fimages%2Fcrop%2F2023%2F09%2F08%2F1694173578_scanpix-20230908-132100-7.jpg&amp;scaleAfter=crop&amp;quality=30&amp;w=2550&amp;h=1434"}]
```

Last piece of the puzzle: Calling https://asset.dr.dk/imagescaler/?protocol=https&amp;server=www.dr.dk&amp;file=%2Fimages%2Fcrop%2F2023%2F09%2F08%2F1694173578_scanpix-20230908-132100-7.jpg&amp;scaleAfter=crop&amp;quality=30&amp;w=2550&amp;h=1434 (note the `&amp;`s) **also works**!

Therefore I conclude:
1. DR's asset server is lenient and turns `&amp;` into `&`
2. KB's harvester does not properly entity-decode the image URL in this situation and harvests the image with `&amp;` (which DR's asset server leniently serves)
3. The warc-indexer does the right thing and indexes the strange `&amp;`-using URLs as-is in `url` and normalised in `url_norm`
4. SolrWayback's `HtmlUrlParserRewriter` does the right thing and produces `https://asset.dr.dk/imagescaler/?protocol=https&server=www.dr.dk&file=/images/crop/2023/09/08/1694173578_scanpix-20230908-132100-7.jpg&scaleafter=crop&quality=30&w=2550&h=1434`, which works perfectly if it is un-normalised to use `https` instead of `http`

And yeah, irritating to fix as it is the data (the harvest) that are the problem. We could - yet again - extend the URL resolver to try a version of the URL where `&` has been converted to `&amp;`.

**Comment by thomasegense** [comment]
This is quite complicated.. Before I am conviced @tokee, I must understand why 

1) If you normalized the url normalize with java code (same result from url-search in frontend), you get:
http://asset.dr.dk/imagescaler/?protocol=https&server=www.dr.dk&file=/images/crop/2023/09/08/1694173578_scanpix-20230908-132100-7.jpg&scaleafter=crop&quality=30&w=2550&h=1434
And this url_norm can be found

2) When you normalize with the HtmlParserUrlRewriter, then you get another result, and one that will not be found.

The only difference is in the HtmlParserUrlRewriter and UrlNormalizer is some logic with AMPERSAND_REPLACE (See line 403)
https://github.com/netarchivesuite/solrwayback/blob/cd0e58a1ad1e3cf37739368b22481d6512f9ea25/src/main/java/dk/kb/netarchivesuite/solrwayback/parsers/HtmlParserUrlRewriter.java#L403

You may still be right that the harvester job is not doing it perfect, but it should work.

**Comment by tokee** [comment]
Please provide the input as well as the output for your call to `Normalisation.canonicaliseURL(url)`

**Comment by thomasegense** [comment]
```
String url="https://asset.dr.dk/imagescaler/?protocol=https&amp;server=www.dr.dk&amp;file=%2Fimages%2Fcrop%2F2023%2F09%2F08%2F1694173578_scanpix-20230908-132100-7.jpg&amp;scaleAfter=crop&amp;quality=30&amp;w=2550&amp;h=1434";
System.out.println(Normalisation.canonicaliseURL(url));
      


Output:
http://asset.dr.dk/imagescaler/?protocol=https&amp;server=www.dr.dk&amp;file=/images/crop/2023/09/08/1694173578_scanpix-20230908-132100-7.jpg&amp;scaleafter=crop&amp;quality=30&amp;w=2550&amp;h=1434
```

**Comment by thomasegense** [comment]
I am convinced. HtmlParserUrlRewriter does decode the url (as it should), so that is why result is different.

Conclusion:
KB's custom 'img src-set' does not decode the URL correct when writing the URL to the warc-filer.
Only reason images are harvested is because the DR's site is lenient and also accepts the wrongly encoded url.
@stephunt  Something you can look into?
