### ISSUE TITLE
ReplayWebPage?

### ISSUE THREAD

**Issue by edsu** [netarchivesuite/solrwayback#457]
I apologize in advance if this is a naive question. Has there been any discussion of moving the playback over to use ReplayWebPage instead of embedding OpenWayback or relying on an external OpenWayback or PyWB?

**Comment by thomasegense** [comment]
No, you will need a external PyWB server etc. and change the properties (solrwaybackweb.properties) to use the PyWB
as primary or alternative playback engine. So you have to index to a CDX server as well. (but this is fast).
This is the Hybrid solution that seems to be the popular choice. France/Luxembourg/Norway and also Denmark are going down this road. SolrWayback for discovery+tools and PyWb/Outback for playback.

Back to your question. There has been discussion if it was possible to also use the Solr index as a CDX index. In theory it is possible by implementing the CDX API method on SolrWayback using the Solr Index data. Unfortunately it would be a very limited CDX index since POST requests are not URL indexed.  So playback  would not be better on PyWB and there will be zero benefit for all this work

If the Warc-Indexer at some point can handle POST requests. **See:** https://github.com/ukwa/webarchive-discovery/issues/244

Then it will be possible to user the Solr index as a much better CDX server. But it will also require some additional fields in Solr for the URL prefix search. And it is hard to tell what performance is for  large 60B documents collections as the one we have en Danmark.  The Outback CDX server is made with the single purpose to optimize the prefix url searches, while Solr is optimized for text search.

Since  Andy is no longer working on the  warc-indexer and we unfortunately do not have Toke anymore,  it is unlikely this will be implemented.  In my opinion it is also two completely seperate tools. It just happens that SolrWayback has a build in playback engine. It SolrWayback did not have playback  noone would probably have given this a thought :) 
Whenever a new/better rules for POST requests are implemented in PYWB+Outback , it would also have to be changed in both the WARC-Indexer and maybe SolrWayback as well. So I would rather not have SolrWayback dependant on latest playback technologi.

**Comment by edsu** [comment]
I see ok, thanks for the clarification! It seems to me like there might be an opening for a new tool that uses lessons learned from pywb, openwayback, solrwayback and outbackcdx which:

1. uses replayweb for playback
2. provides a CDX API and content endpoints (for retrieving content from WARC files)
3. has an index that can support both fulltext, and cdx lookups

But like you said, many institutions have existing infrastructure that solwayback fits into. But for organizations just starting out it all seems a bit complicated and tangled.
