### ISSUE TITLE
Add support for chunked content

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#58]
[Transfer-Encoding: chunked](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding) is used when the size of the content is not known beforehand by the server. This is normally handled internally by the client by "un-chunking", so when we're using `curl`, `wget`, `Heritrix` and most other products we get the original content and can ignore this header.

However, judging by https://github.com/ukwa/webarchive-discovery/issues/218 the tool `warcio` returns the "chunked" version of the content. This makes it a bit of a mess as we can have content marked with [Transfer-Encoding: chunked](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Transfer-Encoding) that is indeed chunked and content that is unchunked, with no explicit indication of whether the un-chunking has been performed or not.

The pull request https://github.com/ukwa/webarchive-discovery/pull/220/files add the method `InputStream maybeDechunk(InputStream input)` that uses heuristics to check is a stream has been de-chunked or not and always return a de-chunked stream.

**Comment by vitezg** [comment]
This is an issue for warc files created by [brozzler](https://github.com/internetarchive/brozzler) too - brozzler's warcprox simply adds to the warc file whatever comes down the connection, thus chunk-encoded content gets saved without unchunking it. Viewing such a warc record causes solrwayback to send a single-line error message: "Not in GZIP format" . I've attached a minimal warc file to demonstrate the issue.
[mekmini-20201029121731465-00000-40fpi1c3.warc.gz](https://github.com/netarchivesuite/solrwayback/files/5458356/mekmini-20201029121731465-00000-40fpi1c3.warc.gz)

**Comment by thomasegense** [comment]
We also found this bug when harvesting with WGET and it will be fixed while we working on the complete rewrite of the GUI with many new features. Also Brotli encoding has been fixed. This was also first fixed in the warc-indexer recently. Can you index the file without getting an error? Else you also need a newer version of the warc-indexer also as toke wrote. As long as it has been indexed correct, it will work in the next release of SolrWayback.

We have been working on a complete GUI rewrite of the solrwayback frontend and it almost feature complete besides a lot of new features and bug fixes.I guess it will be ready in 2-3 weeks with a stable version. I will contact you again when the release is ready.
Upgrade only require new version of the  WAR-file and remove+adding a few properties in the property-file.

**Comment by vitezg** [comment]
Indexing works fine for this one, though we've seen other warc files for which the indexer reports gzip errors. We still need to investigate and narrow down those problems.

**Comment by thomasegense** [comment]
If you can find a warc-fil, with this gzip bug just share it with us.
I have seen it also, but it was also due to truncated content, the webserver did not complete the transfer and the file was
corrupt. The warc-header can tell if content is truncated, but it can be truncated without it shows in the warc-header.

**Comment by tokee** [comment]
@vitezg thank you for the report on the indexer and problems with gzip. It was (primarily) a problem with dechunking, which manifested as gzip-exceptions. The issue has been solved in the pull request https://github.com/ukwa/webarchive-discovery/pull/232 and will hopefully be propagated through the `webarchive-discovery` and the `SolrWayback` code bases soon.

**Comment by vitezg** [comment]
@thomasegense @tokee thanks a lot, we'll start reindexing next week, will report back would anything pop up.

**Comment by thomasegense** [comment]
I have also index the problematic warc file and tested  the new solrwayback version can playback the chuncked transfer encoding.
I have mailed you screenshots.

**Comment by tokee** [comment]
It seems that `brozzler` is great for hardening code. I have opened https://github.com/ukwa/webarchive-discovery/issues/233 and https://github.com/ukwa/webarchive-discovery/issues/234 because of that. They are now fixed in the https://github.com/ukwa/webarchive-discovery/pull/232 pull request.

https://github.com/ukwa/webarchive-discovery/issues/234 (where to perform the digest when the content needs to be dechunked and/or decompressed) is problematic, as it is hard to make an implementation that works well with WARCs delivered from multiple sources. Currently it is done using an option, but a more consistent and auto-detecting solution is needed.

**Comment by thomasegense** [comment]
@vitezg Toke fixed a few bugs yesterday and has commited to the same branch https://github.com/ukwa/webarchive-discovery/pull/232
 So pull again if you already build the warc-indexer jar. 
The will be warnings warnings in the index-log about incorrect hashes, but that will not influence search or playback in a way.
