### ISSUE TITLE
Warming queries

### ISSUE THREAD

**Issue by tokee** [netarchivesuite/solrwayback#64]
Solr is responsible for warming the underlying searcher, but some queries are heavy even with a warmed Solr. If we implement #63, we should also add an option for issuing warming queries when SolrWayback is started (and potentially refresh it once a day or so) to fill the cache with relevant entries.

**Comment by thomasegense** [comment]
The warming seems to only help the first query, and this is probably mostly the case for our Danish Netarkiv because of the large filter query with restrictions(blocked domain/url). The first *:* takes time, but is now cached. The IndexWatcher (enabled by default now) does an initial Solr call, so it is not stone cold. 

Also the use-case for most known SolrWayback  installations is that restart is not happening very often, so the benefit is questionable.  Closing this as there are more important stuff. Will re-open if I heard a community feature requests for it.
